#!/usr/bin/env python3
"""
GranasSabre - in-game volume bar for the menu sounds of
Grandia II HD Remaster / Anniversary Edition (PC).

Adds a fourth row "System sounds" with a volume bar to the in-game config
menu (Menu -> Quit/Config). Left/right changes the volume of the menu sounds
(cursor, confirm, cancel) in 11 steps. The level is stored in the save data.

The tool patches your own grandia2.exe and the menu text files locally.
No game files are shipped.

Usage
-----
  GranasSabre patch   [--game-dir DIR] [--default-level 6] [--step-db 3] [--ids 1,2,3]
  GranasSabre restore [--game-dir DIR]
  GranasSabre status  [--game-dir DIR]
  GranasSabre report  [--game-dir DIR]   (compatibility info to copy & paste)

Run without arguments for an interactive mode.
"""
import argparse
import base64
import hashlib
import json
import os
import re
import shutil
import struct
import sys
import zlib

VERSION = "0.1-beta"
TOOL_NAME = "GranasSabre"
EXE_NAME = "grandia2.exe"
BACKUP_DIR = os.path.join(TOOL_NAME, "backup")   # relative to the game folder
TEXT_DIR = os.path.join("content", "data", "text")
LANGUAGES = ("de", "en", "fr", "ja")
STEAM_APP_ID = "330390"
IMAGE_BASE = 0x400000

# Known unmodified grandia2.exe builds (SHA-256). Unknown builds are refused.
KNOWN_VERSIONS = {
    "06ad6c88778409f65dd111493faf57c3dd92f3292edd6a8ce6ea0109ee5d630e":
        "build 2020-07-31 (PE timestamp 0x5F2448F7)",
}

HOOK_VA = 0x5EF7A9          # first patched instruction; 0xE9 (jmp) when patched

# Known system sound IDs (sound_indices.csv, category 05,01)
SYSTEM_SOUNDS = {
    1: "cursor", 2: "confirm", 3: "cancel", 4: "ipw0022", 5: "page12m",
    8: "caution0b1", 9: "get0122", 10: "heal01a", 11: "cash0044", 12: "Cntup01b",
    13: "item122", 15: "EncountGR2", 16: "caution02", 17: "Status01", 19: "wniz",
    20: "syn00p", 30: "cion02", 31: "up0322", 32: "down0322", 33: "coin0522",
    34: "oku01",
}
DEFAULT_IDS = [1, 2, 3]
DEFAULT_LEVEL = 6
DEFAULT_STEP_DB = 3.0

TEXT_MARKER = "*** GRANASSABRE"
TEXTS = {
    #       label            help text
    "de": ("Systemsounds", "Lautstärke der Menü-Sounds"),
    "en": ("System sounds", "Volume of the menu sounds"),
    "fr": ("Sons système", "Volume des sons du menu"),
    "ja": ("システム音", "メニュー効果音の音量"),
}

# Generated by the build step (code section + byte patches), zlib + base64.
PATCH_DATA = "@@PATCH_DATA@@"


def patch_desc():
    return json.loads(zlib.decompress(base64.b64decode(PATCH_DATA)))


# --- PE helpers --------------------------------------------------------------
class PE:
    def __init__(self, data):
        self.pe = struct.unpack_from("<I", data, 0x3C)[0]
        if data[self.pe:self.pe + 4] != b"PE\0\0":
            raise ValueError("not a PE file")
        self.nsec_off = self.pe + 6
        self.nsec = struct.unpack_from("<H", data, self.nsec_off)[0]
        self.opt = self.pe + 24
        opt_size = struct.unpack_from("<H", data, self.pe + 20)[0]
        self.image_base = struct.unpack_from("<I", data, self.opt + 28)[0]
        self.sect_align = struct.unpack_from("<I", data, self.opt + 32)[0]
        self.file_align = struct.unpack_from("<I", data, self.opt + 36)[0]
        self.size_of_headers = struct.unpack_from("<I", data, self.opt + 60)[0]
        self.sec_tbl = self.opt + opt_size
        self.sections = []
        for i in range(self.nsec):
            o = self.sec_tbl + 40 * i
            name = data[o:o + 8].rstrip(b"\0").decode("ascii", "replace")
            vsize, va, rsize, rptr = struct.unpack_from("<IIII", data, o + 8)
            self.sections.append(dict(name=name, vsize=vsize, va=va, rsize=rsize, rptr=rptr))

    def va_to_off(self, va):
        rva = va - self.image_base
        for s in self.sections:
            if s["va"] <= rva < s["va"] + max(s["vsize"], s["rsize"]):
                return rva - s["va"] + s["rptr"]
        raise ValueError("VA %#x not mapped" % va)


def sha256(data):
    return hashlib.sha256(data).hexdigest()


def looks_patched(data):
    try:
        pe = PE(data)
        return data[pe.va_to_off(HOOK_VA)] == 0xE9
    except Exception:
        return False


def level_gains(levels, step_db):
    top = levels - 1
    return [0.0] + [10.0 ** (-(top - l) * step_db / 20.0) for l in range(1, levels)]


def compat_check(data, desc):
    """Return (ok, problems). ok = every patch site and the PE layout match."""
    try:
        pe = PE(data)
    except ValueError as e:
        return False, [str(e)]
    bad = []
    for p in desc["patches"]:
        try:
            o = pe.va_to_off(p["va"])
        except ValueError:
            bad.append("%#x unmapped" % p["va"])
            continue
        old = bytes.fromhex(p["orig"])
        if data[o:o + len(old)] != old:
            bad.append("%#x differs" % p["va"])
    end = max(x["va"] + -(-max(x["vsize"], x["rsize"]) // pe.sect_align) * pe.sect_align
              for x in pe.sections)
    if pe.image_base != IMAGE_BASE:
        bad.append("image base %#x" % pe.image_base)
    if end != desc["section"]["rva"]:
        bad.append("image end %#x" % end)
    if len(data) % pe.file_align:
        bad.append("file size not aligned")
    if pe.sec_tbl + 40 * (pe.nsec + 1) > pe.size_of_headers:
        bad.append("no room for a section header")
    return not bad, bad


def apply_patch(orig, desc, gains, default_level, id_mask):
    data = bytearray(orig)
    pe = PE(data)
    # 1) byte patches, each checked against the expected original bytes
    for p in desc["patches"]:
        o = pe.va_to_off(p["va"])
        old = bytes.fromhex(p["orig"])
        if data[o:o + len(old)] != old:
            raise ValueError("unexpected bytes at %#x" % p["va"])
        data[o:o + len(old)] = bytes.fromhex(p["new"])
    # 2) new section with code, tables and settings
    s = desc["section"]
    new_hdr = pe.sec_tbl + 40 * pe.nsec
    if new_hdr + 40 > pe.size_of_headers or any(data[new_hdr:new_hdr + 40]):
        raise ValueError("no room for a section header")
    end = max(x["va"] + -(-max(x["vsize"], x["rsize"]) // pe.sect_align) * pe.sect_align
              for x in pe.sections)
    if s["rva"] != end or len(data) % pe.file_align:
        raise ValueError("unexpected image layout")
    raw = bytearray(bytes.fromhex(s["data"]))

    def put(va, b):
        o = va - IMAGE_BASE - s["rva"]
        raw[o:o + len(b)] = b
    put(desc["level_gain_va"], struct.pack("<%df" % len(gains), *gains))
    put(desc["default_level_va"], bytes([default_level]))
    put(desc["id_mask_va"], bytes(1 if m else 0 for m in id_mask))
    rsize = -(-len(raw) // pe.file_align) * pe.file_align
    hdr = s["name"].encode().ljust(8, b"\0") + struct.pack(
        "<IIIIIIHHI", s["size"], s["rva"], rsize, len(data), 0, 0, 0, 0, 0xE0000060)
    data[new_hdr:new_hdr + 40] = hdr
    struct.pack_into("<H", data, pe.nsec_off, pe.nsec + 1)
    struct.pack_into("<I", data, pe.opt + 56, s["rva"] + -(-s["size"] // pe.sect_align) * pe.sect_align)
    # 3) the new code uses absolute addresses -> load at the fixed image base
    dc = struct.unpack_from("<H", data, pe.opt + 70)[0]
    struct.pack_into("<H", data, pe.opt + 70, dc & ~0x0040)
    data += raw + b"\0" * (rsize - len(raw))
    return bytes(data)


def read_settings(data, desc):
    pe = PE(data)
    s = next(x for x in pe.sections if x["name"] == desc["section"]["name"])

    def get(va, n):
        o = va - IMAGE_BASE - s["va"] + s["rptr"]
        return data[o:o + n]
    gains = struct.unpack("<%df" % desc["levels"], get(desc["level_gain_va"], 4 * desc["levels"]))
    default = get(desc["default_level_va"], 1)[0]
    mask = get(desc["id_mask_va"], desc["id_entries"])
    return gains, default, [i for i, m in enumerate(mask) if m]


# --- text files ------------------------------------------------------------
def text_encoding(raw, lang):
    if raw.startswith(b"\xef\xbb\xbf"):
        return "utf-8"
    return "cp932" if lang == "ja" else "utf-8"


def text_block(lang, levels):
    label, help_text = TEXTS[lang]
    lines = [TEXT_MARKER,
             "gs_system_sounds=%s " % label,
             "gs_system_sounds_help=%s    " % help_text]
    top = levels - 1
    for lv in range(levels):
        # the game requires a '/' in option texts; the part before it is highlighted
        lines.append("gs_bar_%s=%s   " % (chr(ord("a") + lv), "|" * lv + "/" + "." * (top - lv)))
    return "\r\n".join(lines) + "\r\n"


def patched_text(raw, lang, levels):
    add = text_block(lang, levels).encode(text_encoding(raw, lang))
    if not raw.endswith(b"\n"):
        add = b"\r\n" + add
    return raw + add


# --- game directory discovery ---------------------------------------------
def steam_candidates():
    roots = []
    try:
        import winreg
        for hive, key, val in [
            (winreg.HKEY_CURRENT_USER, r"Software\Valve\Steam", "SteamPath"),
            (winreg.HKEY_LOCAL_MACHINE, r"SOFTWARE\WOW6432Node\Valve\Steam", "InstallPath"),
        ]:
            try:
                with winreg.OpenKey(hive, key) as k:
                    roots.append(winreg.QueryValueEx(k, val)[0])
            except OSError:
                pass
    except ImportError:
        pass
    libs = []
    for r in roots:
        libs.append(r)
        vdf = os.path.join(r, "steamapps", "libraryfolders.vdf")
        if os.path.isfile(vdf):
            with open(vdf, encoding="utf-8", errors="replace") as f:
                libs += [p.replace("\\\\", "\\") for p in re.findall(r'"path"\s+"([^"]+)"', f.read())]
    out = []
    for lib in dict.fromkeys(libs):
        acf = os.path.join(lib, "steamapps", "appmanifest_%s.acf" % STEAM_APP_ID)
        if os.path.isfile(acf):
            with open(acf, encoding="utf-8", errors="replace") as f:
                m = re.search(r'"installdir"\s+"([^"]+)"', f.read())
            if m:
                out.append(os.path.join(lib, "steamapps", "common", m.group(1)))
    return out


def find_game_dir(arg):
    if arg:
        return arg
    here = os.path.dirname(os.path.abspath(sys.executable if getattr(sys, "frozen", False) else __file__))
    # tool folder itself, its parent (GranasSabre inside the game folder), cwd, Steam
    for c in [here, os.path.dirname(here), os.getcwd()] + steam_candidates():
        if os.path.isfile(os.path.join(c, EXE_NAME)):
            return c
    return None


# --- commands --------------------------------------------------------------
def load(path):
    with open(path, "rb") as f:
        return f.read()


def write_atomic(path, data):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    tmp = path + ".tmp"
    with open(tmp, "wb") as f:
        f.write(data)
    os.replace(tmp, path)


def text_path(base, lang):
    return os.path.join(base, TEXT_DIR, lang, "strings.txt")


def backup_text_path(game, lang):
    return os.path.join(game, BACKUP_DIR, "text", lang, "strings.txt")


def backup_info(game):
    try:
        with open(os.path.join(game, BACKUP_DIR, "backup.json"), encoding="utf-8") as f:
            return json.load(f)
    except (OSError, ValueError):
        return {}


def trusted_original(game, data):
    """A known build, or the unknown build the user explicitly accepted before."""
    h = sha256(data)
    return h in KNOWN_VERSIONS or h == backup_info(game).get("exe_sha256")


def version_label(h):
    return KNOWN_VERSIONS.get(h, "unknown build %s, accepted with --allow-unknown" % h[:16])


def get_original_exe(game, allow_unknown=False):
    exe = os.path.join(game, EXE_NAME)
    cur = load(exe)
    h = sha256(cur)
    if h in KNOWN_VERSIONS:
        return cur
    bak = os.path.join(game, BACKUP_DIR, EXE_NAME)
    if looks_patched(cur):
        if os.path.isfile(bak) and trusted_original(game, load(bak)):
            return load(bak)
        sys.exit("ERROR: %s is already patched, but no valid backup was found." % EXE_NAME)
    ok, problems = compat_check(cur, patch_desc())
    if allow_unknown and ok:
        print("WARNING: unknown %s version, but all patch locations match. Patching anyway." % EXE_NAME)
        return cur
    sys.exit("ERROR: unknown %s version (SHA-256 %s).\n"
             "Nothing was changed. Patch locations: %s.\n"
             "Please run 'GranasSabre report' and post the result."
             % (EXE_NAME, h, "all match (you can try --allow-unknown)" if ok else ", ".join(problems)))


def cmd_patch(game, default_level, step_db, ids, allow_unknown=False):
    desc = patch_desc()
    exe = os.path.join(game, EXE_NAME)
    orig = get_original_exe(game, allow_unknown)
    label = version_label(sha256(orig))
    mask = [i in ids for i in range(desc["id_entries"])]
    try:
        patched = apply_patch(orig, desc, level_gains(desc["levels"], step_db), default_level, mask)
    except ValueError as e:
        sys.exit("ERROR: %s. Nothing was changed." % e)

    # texts: always start from the original file
    texts = {}
    for lang in LANGUAGES:
        p = text_path(game, lang)
        if not os.path.isfile(p):
            continue
        cur = load(p)
        if TEXT_MARKER.encode() in cur:
            b = backup_text_path(game, lang)
            if not os.path.isfile(b):
                sys.exit("ERROR: %s is already modified, but no backup was found." % p)
            base = load(b)
        else:
            base = cur
        texts[lang] = (base, patched_text(base, lang, desc["levels"]))
    if "en" not in texts:
        sys.exit("ERROR: %s not found." % text_path(game, "en"))

    # backup (original exe once, original texts refreshed when they changed)
    bdir = os.path.join(game, BACKUP_DIR)
    bak = os.path.join(bdir, EXE_NAME)
    if os.path.isfile(bak) and sha256(load(bak)) != sha256(orig):
        sys.exit("ERROR: existing backup does not match the original %s. Nothing was changed." % EXE_NAME)
    if not os.path.isfile(bak):
        write_atomic(bak, orig)
    for lang, (base, _) in texts.items():
        b = backup_text_path(game, lang)
        if not os.path.isfile(b) or load(b) != base:
            write_atomic(b, base)
    with open(os.path.join(bdir, "backup.json"), "w", encoding="utf-8") as f:
        json.dump({"tool": TOOL_NAME, "version": VERSION, "exe_sha256": sha256(orig),
                   "exe_version": label, "texts": sorted(texts)}, f, indent=2)

    try:
        write_atomic(exe, patched)
    except PermissionError:
        sys.exit("ERROR: cannot write %s - is the game still running?" % exe)
    for lang, (_, new) in texts.items():
        write_atomic(text_path(game, lang), new)

    print("GranasSabre %s installed (%s)." % (VERSION, label))
    print_settings(level_gains(desc["levels"], step_db), default_level, ids)
    print("Backup: %s" % bdir)


def cmd_restore(game):
    exe = os.path.join(game, EXE_NAME)
    bdir = os.path.join(game, BACKUP_DIR)
    bak = os.path.join(bdir, EXE_NAME)
    if not os.path.isfile(bak):
        if sha256(load(exe)) in KNOWN_VERSIONS:
            print("Nothing to restore: %s is unmodified." % EXE_NAME)
            return
        sys.exit("ERROR: no backup found in %s." % bdir)
    orig = load(bak)
    if not trusted_original(game, orig):
        sys.exit("ERROR: backup file does not match a known original. Nothing was changed.")
    try:
        write_atomic(exe, orig)
    except PermissionError:
        sys.exit("ERROR: cannot write %s - is the game still running?" % exe)
    for lang in LANGUAGES:
        p, b = text_path(game, lang), backup_text_path(game, lang)
        if os.path.isfile(p) and os.path.isfile(b) and TEXT_MARKER.encode() in load(p):
            write_atomic(p, load(b))
    shutil.rmtree(bdir)
    print("Restored the original game files and removed the backup.")


def cmd_status(game):
    exe = os.path.join(game, EXE_NAME)
    cur = load(exe)
    h = sha256(cur)
    if h in KNOWN_VERSIONS:
        print("%s: unmodified, %s" % (EXE_NAME, KNOWN_VERSIONS[h]))
    elif looks_patched(cur):
        try:
            gains, default, ids = read_settings(cur, patch_desc())
            print("%s: patched with GranasSabre %s" % (EXE_NAME, VERSION))
            print_settings(gains, default, ids)
        except StopIteration:
            print("%s: patched with an older GranasSabre version - run 'patch' to update." % EXE_NAME)
    else:
        print("%s: unknown version (SHA-256 %s)" % (EXE_NAME, h))
    for lang in LANGUAGES:
        p = text_path(game, lang)
        if os.path.isfile(p):
            print("  text %s: %s" % (lang, "patched" if TEXT_MARKER.encode() in load(p) else "unmodified"))


def cmd_report(game):
    import datetime
    cur = load(os.path.join(game, EXE_NAME))
    desc = patch_desc()
    data, state = cur, "unmodified"
    if looks_patched(cur):
        state = "patched, no backup found"
        bak = os.path.join(game, BACKUP_DIR, EXE_NAME)
        if os.path.isfile(bak):
            data, state = load(bak), "patched (report uses the backed-up original)"
    h = sha256(data)
    lines = ["GranasSabre %s report" % VERSION,
             "exe state: %s" % state,
             "exe sha256: %s" % h,
             "exe known: %s" % ("yes, " + KNOWN_VERSIONS[h] if h in KNOWN_VERSIONS else "no"),
             "exe size: %d" % len(data)]
    try:
        pe = PE(data)
        ts = struct.unpack_from("<I", data, pe.pe + 8)[0]
        when = datetime.datetime.fromtimestamp(ts, datetime.timezone.utc).strftime("%Y-%m-%d %H:%M")
        lines.append("exe timestamp: %#x (%s UTC)" % (ts, when))
        lines.append("exe sections: %s" % " ".join("%s:%#x" % (x["name"], x["vsize"]) for x in pe.sections))
    except ValueError as e:
        lines.append("exe: %s" % e)
    ok, problems = compat_check(data, desc)
    lines.append("patch locations: %s" % ("all %d match" % len(desc["patches"]) if ok else ", ".join(problems)))
    store = []
    if os.path.isfile(os.path.join(game, "steam_api.dll")):
        store.append("steam_api.dll")
    if any(f.lower().startswith("goggame") for f in os.listdir(game)):
        store.append("goggame files")
    lines.append("store files: %s" % (", ".join(store) or "none found"))
    lines.append("text languages: %s" % " ".join(l for l in LANGUAGES if os.path.isfile(text_path(game, l))))
    print("\n".join(["-" * 60] + lines + ["-" * 60]))
    print("Copy the block above into your reply. It contains no personal data.")


def print_settings(gains, default, ids):
    import math
    top = len(gains) - 1
    step = -20 * math.log10(gains[top - 1]) if gains[top - 1] > 0 else 0
    print("  Sounds on the bar: %s" % ", ".join("%d (%s)" % (i, SYSTEM_SOUNDS.get(i, "?")) for i in ids))
    print("  Bar: %d steps of %.1f dB, step 0 = mute, step %d = original volume" % (top, step, top))
    db = 20 * math.log10(gains[default]) if gains[default] > 0 else float("-inf")
    print("  Default step for saves without a setting: %d (%+.1f dB)" % (default, db))


def parse_ids(s):
    if s is None:
        return DEFAULT_IDS
    if s == "all":
        return sorted(SYSTEM_SOUNDS)
    ids = [int(x) for x in s.split(",") if x.strip()]
    for i in ids:
        if not 0 <= i < 35:
            sys.exit("ERROR: sound ID %d out of range 0..34" % i)
    return ids


def interactive():
    print("GranasSabre %s - menu sound volume bar for Grandia II" % VERSION)
    print()
    choice = input("[P]atch, [R]estore, [S]tatus, [B]eta test report? ").strip().lower()[:1]
    argv = {"p": ["patch"], "r": ["restore"], "s": ["status"], "b": ["report"]}.get(choice)
    if argv and argv[0] == "patch":
        lv = input("Default bar step 0-10 (0 = mute, 10 = original) [%d]: " % DEFAULT_LEVEL).strip()
        if lv:
            argv += ["--default-level", lv]
    return argv


def main():
    ap = argparse.ArgumentParser(prog=TOOL_NAME, description="Grandia II menu sound volume bar")
    ap.add_argument("command", choices=["patch", "restore", "status", "report"])
    ap.add_argument("--game-dir", help="folder containing grandia2.exe")
    ap.add_argument("--default-level", type=int, default=DEFAULT_LEVEL,
                    help="bar step for saves without a setting, 0-10 (default %d)" % DEFAULT_LEVEL)
    ap.add_argument("--step-db", type=float, default=DEFAULT_STEP_DB,
                    help="volume change per bar step in dB (default %g)" % DEFAULT_STEP_DB)
    ap.add_argument("--allow-unknown", action="store_true",
                    help="patch an unknown exe version if all patch locations match")
    ap.add_argument("--ids", help="sound IDs on the bar (default 1,2,3), or 'all' for all system sounds")
    argv = sys.argv[1:]
    pause = not argv
    if not argv:
        argv = interactive()
        if not argv:
            return
    try:
        args = ap.parse_args(argv)
        if not 0 <= args.default_level <= 10:
            ap.error("--default-level must be 0..10")
        if not 0.5 <= args.step_db <= 10:
            ap.error("--step-db must be 0.5..10")
        game = find_game_dir(args.game_dir)
        if not game or not os.path.isfile(os.path.join(game, EXE_NAME)):
            sys.exit("ERROR: %s not found. Use --game-dir." % EXE_NAME)
        if args.command == "patch":
            cmd_patch(game, args.default_level, args.step_db, parse_ids(args.ids), args.allow_unknown)
        elif args.command == "restore":
            cmd_restore(game)
        elif args.command == "report":
            cmd_report(game)
        else:
            cmd_status(game)
    finally:
        if pause:
            input("\nPress Enter to exit.")


if __name__ == "__main__":
    main()
